version: '3.8'

services:
  worker:
    build: .
    environment:
      - SQS_QUEUE_URL=${SQS_QUEUE_URL:-http://localstack:4566/000000000000/fhir-ingestion.fifo}
      - DB_URI=${DB_URI:-mongodb://mongo-hc:27017}
      - DB_USER=${DB_USER:-hospital}
      - DB_PWD=${DB_PWD:-hc123}
      - HCA_DB=${HCA_DB:-fhir_hca}
      - HCB_DB=${HCB_DB:-fhir_hcb}
    volumes:
      - "./logs:/app/logs"
    networks:
      - fhir-network

networks:
  fhir-network:
    external: true